name: Build & publish feeds

on:
  # Run nightly (05:17 UTC). Adjust as you like.
  schedule:
    - cron: "17 5 * * *"
  # Manual run button in Actions
  workflow_dispatch:
  # Also rebuild on source/config changes
  push:
    branches: [ main ]
    paths:
      - "feeds.yaml"
      - "scripts/**"

permissions:
  contents: write

jobs:
  build:
    name: Refresh feeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then
            pip install -r scripts/requirements.txt
          else
            pip install pyyaml feedparser requests beautifulsoup4 lxml
          fi

      - name: Build Boston Dynamics feed
        run: |
          if [ -f scripts/build_boston_dynamics_feed.py ]; then
            python scripts/build_boston_dynamics_feed.py
          else
            echo "No BD builder found, skipping."
          fi

      - name: Build area feeds (AI/Robotics/Quantum/Biotech/Nanotech/Human Effect/Space/Space Force, etc.)
        run: |
          python scripts/build_area_feeds.py

      - name: List generated feeds
        run: |
          echo "Root:"
          ls -lah | sed -n '1,200p'
          echo "feeds/:"
          ls -lah feeds | sed -n '1,200p'

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-refresh feeds [skip ci]"
            git push
          fi
