name: Update Area Feeds (AI/Robotics/Quantum/Biotech/Nanotech)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes

concurrency:
  group: area-feeds
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build area feeds
        run: |
          python scripts/build_area_feeds.py

      - name: Commit generated files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: update feeds & index [skip ci]"
          git push
