name: Update Boston Dynamics RSS

on:
  workflow_dispatch: {}
  schedule:
    # Twice per day (UTC). Adjust as needed.
    - cron: "17 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Build feeds (RSS, Atom, JSON)
        run: python scripts/build_boston_dynamics_feed.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add boston-dynamics-blog.xml \
                   boston-dynamics-blog.atom.xml \
                   boston-dynamics-blog.json
            git commit -m "chore: auto-refresh BD blog feeds (RSS/Atom/JSON) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
