name: Update Space & Defense Feeds

on:
  workflow_dispatch: {}
  schedule:
    # Staggered from the area-feeds job (runs at :07 and :37 past the hour)
    - cron: "7,37 * * * *"

concurrency:
  group: space-defense-feeds
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Build Space & Defense feeds
        env:
          FEED_AREAS: "space-tech,space-force"
        run: |
          python scripts/build_area_feeds.py

      - name: Commit generated files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore(space-defense): update space-tech & space-force feeds [skip ci]"
          git push
