name: Update Area Feeds (AI/Robotics/Quantum/Biotech/Nanotech)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes (UTC)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml pyyaml
      - name: Build area feeds
        run: python scripts/build_area_feeds.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add feeds/ai.* feeds/robotics.* feeds/quantum.* feeds/biotech.* feeds/nanotech.* index.html
            git commit -m "chore: auto-refresh area feeds (AI/Robotics/Quantum/Biotech/Nanotech) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
